#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
import os
import json
import sys
# agent is a NethServer library which provides function to communicate with the agent
import agent
import secrets

data = json.load(sys.stdin)

# Setup default values
random_key = secrets.token_hex(32)
APP_KEY = data.get("APP_KEY",random_key)

# Talk with agent using file descriptor.

app_key = {
    "APP_KEY": APP_KEY
}
agent.write_envfile('key.env', app_key)

# Make sure everything is saved inside the environment file
# just before starting systemd unit
agent.dump_env()